services:
  # Фронтенд-приложение (Vite)
  website:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_POCKETBASE_URL: ${VITE_POCKETBASE_URL}
        VITE_LASTFM_API_KEY: ${VITE_LASTFM_API_KEY}
    ports:
      - "5173:3000"
    depends_on:
      - pocketbase
    restart: unless-stopped

  # Панель управления, база данных и REST API (PocketBase)
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    env_file:
      - .env
    volumes:
      - pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks:ro
    restart: unless-stopped

volumes:
  pb_data:
